-- Crear base de datos
CREATE DATABASE presentacion ENCODING = 'UTF8' CONNECTION LIMIT = 9;

-- Crear administrador
CREATE USER administrador WITH LOGIN ENCRYPTED PASSWORD 'admin123' SUPERUSER CREATEDB CREATEROLE;


-- Crear usuarios comunes
CREATE USER agus WITH LOGIN ENCRYPTED PASSWORD 'agus123' NOSUPERUSER NOCREATEDB NOCREATEROLE CONNECTION LIMIT 1;
CREATE USER elias WITH LOGIN ENCRYPTED PASSWORD 'elias123' NOSUPERUSER NOCREATEDB NOCREATEROLE CONNECTION LIMIT 1;
CREATE USER ignacio WITH LOGIN ENCRYPTED PASSWORD 'ignacio123' NOSUPERUSER NOCREATEDB NOCREATEROLE CONNECTION LIMIT 1;
CREATE USER pedro WITH LOGIN ENCRYPTED PASSWORD 'pedro123' NOSUPERUSER NOCREATEDB NOCREATEROLE CONNECTION LIMIT 1;
CREATE USER manu WITH LOGIN ENCRYPTED PASSWORD 'manu123' NOSUPERUSER NOCREATEDB NOCREATEROLE CONNECTION LIMIT 1;
CREATE USER pablo WITH LOGIN ENCRYPTED PASSWORD 'pablo123' NOSUPERUSER NOCREATEDB NOCREATEROLE CONNECTION LIMIT 1;
CREATE USER fran WITH LOGIN ENCRYPTED PASSWORD 'fran123' NOSUPERUSER NOCREATEDB NOCREATEROLE CONNECTION LIMIT 1;
CREATE USER baltasar WITH LOGIN ENCRYPTED PASSWORD 'baltasars123' NOSUPERUSER NOCREATEDB NOCREATEROLE CONNECTION LIMIT 0;


-- Dar permisos de conexión a ambos usuarios sobre la base de datos
GRANT CONNECT ON DATABASE presentacion TO agus, elias, ignacio, pedro, manu, pablo, fran, baltasar;

GRANT CONNECT ON DATABASE presentacion TO administrador;